import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider_ from "./providers/ThemeProvider";
import Sidebar from "./components/shared/Sidebar";
import MarketProvider from "./providers/MarketProvider";
import { FetchMarket } from "./lib/fetch";
import "@/app/lib/fontawesome";
import CursorFollower from "./components/shared/CursorFollower";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const marketData = await FetchMarket();

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CursorFollower />
        <ThemeProvider_>
          <MarketProvider marketData={marketData}>
            <div className="min-h-screen flex bg-white dark:bg-black">
              <Sidebar />
              <main className="flex-1 min-w-0 p-4 lg:p-6">{children}</main>
            </div>
          </MarketProvider>
        </ThemeProvider_>
      </body>
    </html>
  );
}
